package oop_Review.Exceptions;

/* public class Example2 {
    public static void main(String[] args) {
        //Example 1
        int x=10, y=1;
        try{
            System.out.println(x/y);
        int data=1/0;

        }
        catch (ArithmeticException e){
            System.out.println("oops division by zero exception");
        }
        //Example 2
        String s=null;
        try {
            System.out.println(s.length());
        }
        catch (Exception e){
            System.out.println("oops");
        }
        String a="a";
        try{
            int number = Integer.parseInt(a);
        }
        catch (Exception e){
            System.out.println("Sorry I could not convert");
        }
        //Example 3
        int numbers[]={1,2,3,4,5};
        try{
            System.out.println(numbers[77]);
        }
        catch (Exception e){

        }

    }
}

 */